#ifndef COLLISION_DEFINES_H
#define COLLISION_DEFINES_H

#define COLLISION_GIRDER_BUILDPOINT 1
#define COLLISION_GIRDER 2
#define COLLISION_BUILDRAYCAST 3
#define COLLISION_ATOM 4

#endif	COLLISION_DEFINES_H