#ifndef COLLISION_DEFINES_H
#define COLLISION_DEFINES_H

#define COLLISION_BUILDPOINT 1
#define COLLISION_GIRDER 2
#define COLLISION_BUILDRAYCAST 4
#define COLLISION_ATOM 8

#endif	COLLISION_DEFINES_H