#ifndef COLLISION_DEFINES_H
#define COLLISION_DEFINES_H

#define COLLISION_BUILDPOINT 1
#define COLLISION_STRUCTURE 2
#define COLLISION_BUILDRAYCAST 4
#define COLLISION_OBJ 8
#define COLLISION_MOB 16
#define COLLISION_TURF 32

#endif	COLLISION_DEFINES_H